### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by Buried-In-Code** [ewels/rich-codex#48]
I've been running this action to keep my doc images up to date, however all my pipelines have stopped working due to a deprecated version of `actions/upload-artifact`.
Something like dependabot would be useful in this case, I can create a PR to add it if it'll be helpful.

Error Message:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

Workflow to replicate issue:
```yaml
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Setup Python
        run: uv python install '3.13'
      - name: Install project
        run: uv sync --dev

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          commit_changes: true
          clean_img_paths: true
```
